export enum ConfigParameter {
  CLIENT_ID = 'CLIENT_ID',
  CLIENT_SECRET = 'CLIENT_SECRET',
  CLUSTER_ID = 'CLUSTER_ID',
  WEBSITESHOT_PROJECT_ID = 'WEBSITESHOT_PROJECT_ID',
  WEBSITESHOT_API_KEY = 'WEBSITESHOT_API_KEY',
  AWS_BUCKET = 'AWS_BUCKET',
  AWS_SECRET_ID = 'AWS_SECRET_ID',
  AWS_SECRET_KEY = 'AWS_SECRET_KEY',
}
